sudo: false
language: node_js
node_js:
  - "14"

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
    - dist
    - .cache

stages:
  - Build
  - Post-build

jobs:
  fast_finish: true

  include:
    - stage: Build
      name: Lint and Build
      before_install: npm install --global yarn
      install: yarn
      script:
        - yarn lint:js || travis_terminate 1
        - yarn lint:markdown || travis_terminate 1
        - yarn lint:social || travis_terminate 1
        - yarn build || travis_terminate 1
        - yarn lint:links || travis_terminate 1

    - stage: Build
      name: Proselint
      language: python
      python: 3.6
      cache:
        pip: true
        directories:
          - $HOME/.cache
      install: pip install -r requirements.txt
      script: cp .proselintrc ~/ && proselint src/content

    - stage: Post-build
      name: Deploy
      if: branch = master AND type IN (push, cron)
      script: bash ./src/scripts/deploy.sh
