dist: bionic
language: node_js
node_js: "12"

cache:
  yarn: true
  npm: false
  directories:
    - .cache
    - repositories

stages:
  - Build

jobs:
  fast_finish: true

    - stage: Build
      name: Build and Deploy
      if: branch = master AND type IN (push, cron)
      env: CACHE_TYPE=build
      script:
        - yarn build || travis_terminate 1
        - yarn lint:links || travis_terminate 1
        - bash ./src/scripts/deploy.sh
